### PR TITLE
adds additional checks on indexing start/end times

### LINKED ISSUE #1304: bedmaster_index.csv incorrect t_start and/or t_end
In the `bedmaster_index.csv` file, there are 1,278,382 indices for `.mat` files.

1. in some (<100) cases, `t_start` is <=0: should we ignore those files? Which waveform/vital's time vector was being checked to get the `t_start`? Is it possible, that parameter was missing in those files?

2. when looking for reasonable file durations, i.e. for `t_delta = t_end - t_start`, finding the index of problematic timestamps `np.where(t_delta<60 | t_delta>600000)` gives 30,215 indices. that means a lot of files have less than a minute's worth data (?!) or something wrong with the timestamp. Again, which waveform/vital's time vector was being checked to get the `t_start`? Is it possible, that parameter was rare in those files?

### LINKED ISSUE #1307: Bedmaster bundles are 1000 minutes by amount of data, not by absolute time
I think it's important to clarify for @aguirre-lab/ml4c3-dev and @contactadityag + @matt-cdac that the bedmaster `.mat` bundles contain 1000 minutes of data by the amount of data and not by the absolute time difference between the earliest and latest timestamp.

This should be clarified here: https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-raw-data#structure

This also affects our discussion in #1304 as we were going to go off the heuristic that a `t_delta > 70,000 seconds` is incorrect, however, it is very possible and occurs in 86K files

here's how I arrived at this finding, the `.mat` file is `ELL18/ELL18_1832B-1607287686_3_v4.mat`. the 2nd to last cell's output shows the amount of data in this `.mat` file, measured in minutes and the last cell shows the absolute difference in time from the first sample to the last sample
 
image

### LINKED ISSUE #1308: Bedmaster time zigzag
within a single `.mat` file, there are jumps back in time and timestamps are repeated

its still 1000ish minutes of data

image

### PR DESCRIPTION
**Pull request by StevenSong**
## Issues closed
Closes #1304 
Closes #1307 

## Changelog
- [x] indexer checks that start is not < 0 and checks that end time is not earlier than start time
- [x] this does not actually solve #1308 but will save an error for the obviously wrong ones where the start time is after the end time

### CODE REVIEW

**Review by RogerPallares — APPROVED** [review]

**Comment by erikr** [comment]
@StevenSong so now we rerun indexer?

**Comment by StevenSong** [comment]
> @StevenSong so now we rerun indexer?

this PR only really addresses 14,000 files where `StartTime` was `-1` and 14 files where `EndTime < StartTime`. I already reindexed those 14K + 14 files

**Review by RidwanAlam — COMMENTED** [review]
Cool! that should do it. Thanks @StevenSong

**Comment by RidwanAlam** [comment]
> > @StevenSong so now we rerun indexer?
> 
> this PR only really addresses 14,000 files where `StartTime` was `-1` and 14 files where `EndTime < StartTime`. 
> I already reindexed those 14K + 14 files

you already did? that's awesome.

**Pull request merged**
