### PR TITLE
Improve plot aesthetics of continuous TMap 1) histograms in explore, and 2) scatterplots of regression predictions

### LINKED ISSUE #872: Improve aesthetics of histograms in scatterplots for continuous TMaps
could look better
Screen Shot 2020-11-25 at 10 14 00 AM

### LINKED ISSUE #1157: Improve explore histograms when stratifying by args.explore_stratify_label
## Question or modeling task

The legend should only have two entries (not four), and histogram bars and outlines for `death` labels should be a different color than for `no_death`:
Screen Shot 2021-01-18 at 1 13 35 AM

Histograms per label should use same bin size.

### PR DESCRIPTION
**Pull request by erikr**
## Issues closed
Closes #872
Closes #1157

## Changelog
- [x] Remove redundant legend entries from KDE plots.
- [x] Use same color for histogram and KDE outline for each label.
- [x] Sort label order for more intuitive color order when stratifying by `args.explore_stratify_label`.
- [x] Select colors from `sns.color_palette()`.
- [x] Sub-histograms have same number of bars when stratifying by `args.explore_stratify_label`.
- [x] Move plot histogram function from `ml4c3/explorations` to `ml4c3/plots`.
- [x] New notebook imports plot histogram function and uses it to plot randomly generated data.
- [x] Change `title` arg to more descriptive `tensor_map_name` in several plot functions.
- [x] Removes box around scatterplot legends.
- [x] Changes some labels to be consistent, e.g. `Actual` should be `Truth` to be consistent with rest of plot and code.
- [x] Adds `/` between correlation statistics in scatterplot legend to improve readability. 

### Explore histogram
**Old**
histogram_hr_all_legacy

**New**
histogram_hr_stratified_all

### Prediction scatterplot
**Old**
scatter-old

**New**
scatter-new

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

### CODE REVIEW

**Comment by StevenSong** [comment]
The plots look much better, a few questions about the histograms:
- in explore histogram, have you checked that it works with categorical (> binary) data?
- in #1157, the issue mentions unequal bin sizing and that still appears to be an issue in these plots, thoughts?

**Comment by erikr** [comment]
> * in explore histogram, have you checked that it works with categorical (> binary) data?

Histograms are only plotted for continuous TMaps
https://github.com/aguirre-lab/ml4c3/blob/04e3f5f281b5910b822796a98d612fadd43147c1/ml4c3/explorations.py#L460-L462

> * in #1157, the issue mentions unequal bin sizing and that still appears to be an issue in these plots, thoughts?
I forgot to address bin size in this PR. Just added that to the changelog, will implement now and push to this branch.

**Comment by erikr** [comment]
> in #1157, the issue mentions unequal bin sizing and that still appears to be an issue in these plots, thoughts?

I forgot to address bin size in this PR. I just pushed a commit that implements equal bin size for unequal data size plots. Please review.

**Comment by erikr** [comment]
Tests fixed.

**Comment by StevenSong** [comment]
in addition to now equal bin size, should edges be shared such that the bars from one histogram do not overlap the edges of another histogram?

**Comment by erikr** [comment]
> in addition to now equal bin size, should edges be shared such that the bars from one histogram do not overlap the edges of another histogram?

Good idea!

**Comment by erikr** [comment]
> in addition to now equal bin size, should edges be shared such that the bars from one histogram do not overlap the edges of another histogram?

Done.

Any preference on `element="bars"` versus `element="step"`?
histogram-hr-stratified-all

histogram_hr_stratified_all_step

**Comment by StevenSong** [comment]
> Any preference on `element="bars"`
> versus `element="step"`?

step looks a little better? it's a little easier to see the blue under the orange with "step"

**Comment by erikr** [comment]
Done, `step` it is.

**Review by StevenSong — APPROVED** [review]
are the changes to clustering example in this PR intentional? @epalto

**Comment by erikr** [comment]
> are the changes to clustering example in this PR intentional? @epalto

The diffs you see are because I ran `nbstripout`. Cell contents were committed to `master` https://github.com/aguirre-lab/ml4c3/blob/master/notebooks/clustering/clustering_example.ipynb.

@epalto you may need to file another sensitive info request to remove, and also ensure your `pre-commit` hooks work.

**Pull request merged**
